name: Build macOS Binaries

on:
  release:
    types:
      - created

jobs:
  masos:
    name: Build macOS binaries
    runs-on: macos-14
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: "DEBUG: What's our directory & what's in it?"
        run: pwd && ls

      - name: Build the uuid7 executables
        run: ./build-macos-executables.sh ${{ github.event.release.tag_name }}
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_IDENTITY_ID: ${{ secrets.MACOS_IDENTITY_ID }}

      - name: List the uuid7 executables
        run: ls -l ./release

      - name: Upload the uuid7 binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/uuid7-*
          file_glob: true
